#!/bin/bash


######################################################
#                   Music_Finder V1.1                #
#  https://gitlab.com/Music_Finder/music-finder.git  #
######################################################


noColor='\033[0m'       # Text mode
# Colors
red='\033[0;31m'          # red
green='\033[0;32m'        # green
orange='\033[0;33m'       # orange
blue='\033[0;34m'         # blue
white='\033[0;37m'        # white

# ----------\Find music function\----------
function findf() {
	local input_dir="$1"
	read -p "Please enter the name of music wich you search : " name
	read -p "Please Select your type d {directory} f {file} : " typelike

	if [[ $typelike == "d" ]]; then
		# Search directory
		sudo find  $dir -type d -iname $name
	elif [[ $typelike == "f" ]]; then
		echo -e "${orange}Install the mplayer if you want to play music after find it${noColor}"
		# Search and play music whit Mplayer
		sudo find $input_dir -type f -iname "*$name*" -exec mplayer {} \;
		# Massage after play music
		#if [[ "$?" == "0" ]]; then
		#	echo -e "${green} Music is completely finished ${noColor}"
		#	exit 0
		#else
		#	echo -e "${red} Music is not completely finished ${noColor}"
		#fi
	else
		echo -e "${red}Your type is not true!${noColor}"
	fi
}

# ----------\Select directory function\----------
function choose_dir() {
	clear

	echo -e "${green}-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/${noColor}"
	echo -e "${orange}Please Select your path ${noColor}"

	read -p "Do you like to serach all of your system (Requires root access)? [Y/n] " all_system

	if [[ "$all_system" == "" || "$all_system" == "y" || "$all_system" == "Y" ]]; then
		# ----------\Search all of file system\----------
	    echo -e "${green}-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/${noColor}"
	    echo -e "This operation may take a while!"

		findf "/"
	elif [[ "$all_system" == "n" || "$all_system" == "N" ]]; then
		read -p "Do you like search this directory? [Y/n] " likedirectory

		if [[ "$likedirectory" == "" || "$likedirectory" == "y" || "$likedirectory" == "Y" ]]; then
			# ----------\Search current directory\----------
		    echo -e "${green}-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/-/${noColor}"

			findf "$PWD"
		elif [[ "$likedirectory" == "n" || "$likedirectory" == "N" ]]; then
			# ----------\Search entered path\----------
			read -p "Enter a directory : " -i "" -e addressdirectory
				if [[ "$addressdirectory" == "/" ]]; then
					echo -e "${red}You have to chose first option :)${noColor}"
				else
					findf "$addressdirectory"
				fi
		else
			echo -e "${red}Invalid argument!${noColor}"
		fi
	else
	    echo -e "${red}Invalid argument!${noColor}"
	fi
	echo -e "${green}done!${noColor}"
}

# ----------\Uninstall function\----------
function uninstall() {
	clear

	read -p "Are you sure to uninstall music-finder??!! [y/N] " delete

	# ----------\Uninstall music-finder\---------
	if [[ "$delete" == "y" || "$delete" == "Y" ]]; then
		del_dependecies="0"
		#Checking if the distro is DebianBase / ArchBase / RedHatBase / SuseBase and running the correct command
		codename="lsb_release -c | awk {'print $2'}"
		architecture="dpkg --print-architecture"
		if pacman -Q &> /dev/null; then # Check Arch
			sudo pacman -Rs mplayer
			# Check user's entered password
			if [[ "$?" == "1" ]]; then
				del_dependecies="1"
			fi
		elif [[ "$codename" == "bionic" ]] && [[ "$architecture" == "armhf" ]]; then # Check Ubuntu Server
			sudo apt remove mplayer
			# Check user's entered password
			if [[ "$?" == "1" ]]; then
				del_dependecies="1"
			fi
		elif apt list --installed &> /dev/null; then # Check Debian
			sudo apt remove mplayer
			# Check user's entered password
			if [[ "$?" == "1" ]]; then
				del_dependecies="1"
			fi
		elif dnf list &> /dev/null; then # Check Fedora
			sudo dnf remove mplayer
			# Check user's entered password
			if [[ "$?" == "1" ]]; then
				del_dependecies="1"
			fi
		elif zypper search i+ &> /dev/null; then # Check openSUSE
			sudo zypper remove mplayer
			# Check user's entered password
			if [[ "$?" == "1" ]]; then
				del_dependecies="1"
			fi
		else
			echo -e "${red}Your distro is neither ArchBase or DebianBase or RedHatBase or SuseBase So, The script is not going to work in your distro and you have uninstall the dependencies manually. for more information read README.md"
			del_dependecies="1"
		fi

		sudo rm -f /usr/bin/music-finder
		# ----------\Removing Music-finder Command\----------
		if [[ "$del_dependecies" == "0" ]]; then
		    echo -e "\n ${red}music-finder succesfully uninstalled :( ${noColor}"
		else
			echo -e "\n ${green}music-finder doesn't uninstall succesfully :) ${noColor}"
			exit 1
		fi
	elif [[ "$delete" == "" || "$delete" == "n" || "$delete" == "N" ]]; then
		echo -e "\n ${green}music-finder is still installed :) ${noColor}"
		exit 0
	else
		echo -e "${red}Invalid argument! ${noColor}"
		exit 1
	fi
}

# ----------\Update fiunction\----------
function update() {
	clear

	if [[ -d /tmp/music_finder ]]; then
		cd /tmp
		git clone https://gitlab.com/Music_Finder/music-finder.git
		sleep 2
		cd music-finder
		sudo cp music-finder /usr/bin/music-finder
		sudo chmod 755 /usr/bin/music-finder
		sudo rm -rf /tmp/music-finder
		echo -e " ${green}Music_Finder updated succesfully! ${noColor}"
	else
		sudo rm -rf /tmp/music_finder
		cd /tmp
		git clone https://gitlab.com/Music_Finder/music-finder.git
		sleep 2
		cd music-finder
		sudo cp music-finder /usr/bin/music-finder
		sudo chmod 755 /usr/bin/music-finder
		sudo rm -rf /tmp/music-finder
	fi
}

# ----------\Help function\----------
function usage() {
	echo -e "\n Usage: music-finder [ -h | --help ],  [ --uninstall ],   [ -U | --update ]"
	exit 1
}

# ----------\Input options\----------
case "$1" in
    "")    choose_dir    ;;
    "--update" | "-U")    update    ;;
	"--uninstall")    uninstall    ;;
	"--help" | "-h")    usage    ;;
	*)    usage    ;;
esac;
exit 0
